### ISSUE TITLE
How to render emoji directly on input element

### ISSUE THREAD

**Issue by KamalakannanPE** [globaldev/angular-emoji-filter#10]
Hi,
Is there any way to render the emoji directly on input / text area instead of rendering only on view element ?

Because we are trying to build chat, in which we show the emoticons in collection like in Whatsapp. Now we are supposed to render the emoticon inside the input element when the user chooses an emoticon

**Comment by danshearmur** [comment]
Hi unfortunately you can't render emoji into inputs or textareas.

The emoji filter works by replacing your emoji code `:dog:` with a span that has some classes (e.g. `<span class="emoji emoji_dog" title="dog"></span>` that set it's size and has a background image of the actual emoji. So you would just end up seeing the HTML in your inputs or textareas.

You may be able to achieve something similar by using [`contenteditable`](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_Editable) on an element, but you would need to re-run the filter after every key press.
